name: Compile CV to PDF and PNG
description: Compiles the CV to PDF and PNG

runs:
  using: composite
  steps:
    - name: Compile cv
      shell: bash
      run: make harry-randazzo-cv.pdf harry-randazzo-cv.png
