name: Compile CV using Typst
description: Compiles the CV using Typst via Docker

runs:
  using: composite
  steps:
    - name: Compile CV using Typst
      shell: bash
      run: |
        brew install typst
        typst compile cv.typ
